# Generated by Django 5.0.3 on 2024-03-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Low', 'Низкий'), ('Medium', 'Средний'), ('High', 'Высокий')], default='Low', max_length=10)),
                ('status', models.CharField(choices=[('New', 'Новая'), ('In Progress', 'В прогрессе'), ('Done', 'Выполнено'), ('Cancelled', 'Отменено'), ('Postponed', 'Отложено')], default='New', max_length=20)),
            ],
        ),
    ]
